import { Inter } from "next/font/google";
// CSS
import "../../public/assets/css/bootstrap.min.css";
import "../../public/assets/css/animate.min.css";
import "../../public/assets/css/magnific-popup.css";
import "../../public/assets/css/magnific-popup.css";
import "../../public/assets/css/fontawesome-all.min.css";
import "../../public/assets/css/flaticon.css";
import "../../public/assets/css/slick.css";
import "../../public/assets/css/default.css";
import "../../public/assets/css/stylee.css";
import "../../public/assets/css/responsive.css";

import "./globals.css";
import { Footer } from "./components/footer/Index";
import { Navbar } from "./components/navbar/Index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" tg-theme="dark">
      <body className={inter.className}>
          <header>
            <Navbar />
          </header>
          <main>
            {children}
          </main>
          <footer>
            <Footer />
          </footer>
      </body>
    </html>
  );
}
